### ISSUE TITLE
`parse_asset_uri` error occued

### ISSUE THREAD

**Issue by ryosuke-endo** [Shopify/sprockets-commoner#57]
I am grateful to this gem.

However, problems occured when deploying production.

There are times when you fail when sass is changed.

As mentioned here as well, I think that cache is probably the cause.

As a brute solution, I did `rm -rf production` and deployed again.

My site was good at the beta version, but I think that it is frightening to think that it happened with production....

Below is the error contents.

```
Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as mikami@sakura: rake exit status: 1
rake stdout: rake aborted!

URI::InvalidURIError: expected file:// scheme: 

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/uri_utils.rb:94:in `parse_asset_uri'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/unloaded_asset.rb:134:in `load_file_params'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/unloaded_asset.rb:64:in `params'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:34:in `load'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-commoner-0.6.3/lib/sprockets/commoner/bundle.rb:71:in `block in call'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-commoner-0.6.3/lib/sprockets/commoner/bundle.rb:65:in `map'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-commoner-0.6.3/lib/sprockets/commoner/bundle.rb:65:in `call'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-commoner-0.6.3/lib/sprockets/commoner/bundle.rb:54:in `call'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:134:in `block in find'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:133:in `each'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:133:in `find'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:185:in `compile'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-3.7.0/lib/rake/sprocketstask.rb:147:in `with_logger'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/sprockets-rails-3.2.0/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'

/var/www/kijochannel/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'

/home/mikami/.rbenv/versions/2.3.1/bin/bundle:23:in `load'

/home/mikami/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'

Tasks: TOP => assets:precompile

(See full trace by running task with --trace)
rake stderr: Nothing written

bundle exec cap production deploy returned exit code 1
```

**Comment by ian** [comment]
Getting the same thing.  Tracked it down to `env.resolve`:

![screen shot 2017-04-06 at 5 01 33 pm](https://cloud.githubusercontent.com/assets/19853/24777400/d0b61dd6-1aea-11e7-8688-5bcdc1ad5aa6.png)

**Comment by ian** [comment]
Scratch that.  File didn't exist.  Seems my assets cache was referring to an older directory.

To fix this you can just blow away your cache: `rm -rf tmp/cache`
